version: 2
updates:
- package-ecosystem: gradle
  directory: "/ChromecastFragmentDemo"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.longtailvideo.jwplayer:jwplayer-chromecast
    versions:
    - 3.19.2
  - dependency-name: com.longtailvideo.jwplayer:jwplayer-common
    versions:
    - 3.19.2
  - dependency-name: com.longtailvideo.jwplayer:jwplayer-core
    versions:
    - 3.19.2
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/ChromecastDemo"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/conviva-integration"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/DemoNativeControls"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/FullBackgroundAudio"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/GoogleDAIDemo"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: junit:junit
    versions:
    - 4.13.2
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/listview-fullscreen"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/LocalAssetPlayback"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/movable-player"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/notifications-demo"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.longtailvideo.jwplayer:jwplayer-common
    versions:
    - 3.19.2
  - dependency-name: com.longtailvideo.jwplayer:jwplayer-core
    versions:
    - 3.19.2
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
- package-ecosystem: gradle
  directory: "/RecyclerViewDemo"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
